server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/purchase
    username: root
    password: root
  #application:
    #name: user-service # 应用名称
mybatis:
  type-aliases-package: com.test.domain